#!/bin/bash
set -x
if [ ! -d $OPENSHIFT_DATA_DIR/gradle-2.6 ]
then
    cd $OPENSHIFT_DATA_DIR
    mkdir gradle
    wget http://services.gradle.org/distributions/gradle-2.6-bin.zip
    unzip gradle-2.6-bin.zip
    rm -f gradle-2.6-bin.zip
fi

if [ ! -d $OPENSHIFT_DATA_DIR/jdk-8u5-linux-x64 ]
then
    cd $OPENSHIFT_DATA_DIR

    wget --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u5-b13/jdk-8u5-linux-x64.tar.gz
    tar -zxf jdk-8u5-linux-x64.tar.gz
    rm -rf jdk-8u5-linux-x64.tar.gz
fi
