database:
  driverClass: org.postgresql.Driver
  user: test
  password: test
  url: jdbc:postgresql://localhost:5432/test
  properties:
    charSet: UTF-8
  maxWaitForConnection: 5s
  validationQuery: "SELECT 1"
  validationQueryTimeout: 3s
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute
mail:
  host: test.test.com
  port: 465
  registrationMailTemplate: "Cześć %s,<br><br>Dziękujemy za zgłoszenie prezentacji.<br>Twoje zgłoszenie zostało dodane do listy zgłoszonych prezentacji i weźmie udział w głosowaniu.<br><br>Zespół DevCrowd"
  registrationMailSubject: "C4P DevCrowd"
  fromAddress: c4p@devcrowd.pl