database:
  driverClass: org.postgresql.Driver
  user: test
  password: test
  url: jdbc:postgresql://localhost:5432/test
  properties:
    charSet: UTF-8
  maxWaitForConnection: 5s
  validationQuery: "SELECT 1"
  validationQueryTimeout: 3s
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute
mail:
  host: test.test.com
  port: 465
  registrationMailTemplate: "Cześć %s,<br><br>Dziękujemy za zgłoszenie prezentacji.<br>Twoje zgłoszenie zostało dodane do listy zgłoszonych prezentacji i weźmie udział w głosowaniu.<br><br>Zespół DevCrowd"
  registrationMailSubject: "C4P DevCrowd"
  participantRegistrationMailTemplate: "Cześć %s,<br><br>Dziękujemy za rejestrację i do zobacznie.<br><br>SuperChicken system i Zespół DevCrowd"
  participantRegistrationMailSubject: "C4P DevCrowd - Rejestracja"
  participantConfirmationMailTemplate: "Cześć %s,<br><br>Konferencja zbliża się wielkimi krokami. Dla lepszej organizacji i sprawniejszej rejestracji w dniu konferencji prosilibyśmy o poświęcenie minuty w celu potwierdzenia przybycia i wyboru preferowanego posiłku pod linkiem <a href='http://devcrowd.pl/confirmation.html?id=%s#confirmation'>potwierdzenie</a><br><br>SuperChicken system i Zespół DevCrowd"
  participantConfirmationMailSubject: "C4P DevCrowd - Rejestracja"
  fromAddress: c4p@devcrowd.pl
  participantRegistrationFromAddress: info@devcrowd.pl
maxVotes: 5
logging:
  level: INFO
  appenders:
    - type: console
    - type: file
      currentLogFilename: ./logs/superchicken.log
      archivedLogFilenamePattern: ./logs/superchicken-%d.log.gz
      archivedFileCount: 5